### ISSUE TITLE
Create VM failed with 'Bosh::AzureCloud::AzureAsynchronousError'

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-azure-cpi-release#359]
### Versions
CPI      Version: 35
BOSH     Version: 264.6
CF       Version:
Diego    Version:

### Stemcell
Version: 3468.13
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
  - [ ] Others:
- Location: West US
- Subscription ID: On request
- Resource Group Name: On request
- [ ] Use Managed Disks

### Issue Details

While upgrading a deployment, we received the following error:

```
Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<Bosh::AzureCloud::AzureAsynchronousError: Bosh::AzureCloud::AzureAsynchronousError>
```

We re-ran the deployment 5 hours later and it failed with the same error, although the deployment made it a bit farther. What is causing this error? Could the CPI better handle this case or return a better error message?

### Logs

Initial stack trace:

```
D, [2018-01-09T03:47:21.145575 #60146] DEBUG -- [req_id cpi-879487]: check_completion - azure-asyncoperation: https://management.azure.com/subscriptions/3ff28d14-86e0-4c6e-aade-9a779f3637a4/providers/Microsoft.Compute/locations/westus/operations/bdd82901-9b57-4c18-9097-44e8b2b6b427?api-version=2016-04-30-preview
D, [2018-01-09T03:47:26.145950 #60146] DEBUG -- [req_id cpi-879487]: check_completion - trying to get the status of asynchronous operation: https://management.azure.com/subscriptions/3ff28d14-86e0-4c6e-aade-9a779f3637a4/providers/Microsoft.Compute/locations/westus/operations/bdd82901-9b57-4c18-9097-44e8b2b6b427?api
-version=2016-04-30-preview
D, [2018-01-09T03:47:26.146192 #60146] DEBUG -- [req_id cpi-879487]: http_get_response - 0: GET, x-ms-client-request-id: 0d6d22e9-499f-4e9d-92c7-26d4d5bbbdbd, URI: https://management.azure.com/subscriptions/3ff28d14-86e0-4c6e-aade-9a779f3637a4/providers/Microsoft.Compute/locations/westus/operations/bdd82901-9b57-4c
18-9097-44e8b2b6b427?api-version=2016-04-30-preview
D, [2018-01-09T03:47:26.429483 #60146] DEBUG -- [req_id cpi-879487]: http_get_response - 0: 200
x-ms-client-request-id: 0d6d22e9-499f-4e9d-92c7-26d4d5bbbdbd
x-ms-request-id: cb210f98-c9bd-4c54-a81e-d1e4035f4e16
x-ms-correlation-request-id: ca5bdb60-cd64-4740-bd70-e90f8e67b180
x-ms-routing-request-id: WESTUS:20180109T034726Z:ca5bdb60-cd64-4740-bd70-e90f8e67b180
response.body: {"startTime":"2018-01-09T03:47:21.7292735+00:00","endTime":"2018-01-09T03:47:21.8229635+00:00","status":"Succeeded","name":"bdd82901-9b57-4c18-9097-44e8b2b6b427"}
I, [2018-01-09T03:47:26.429635 #60146]  INFO -- [req_id cpi-879487]: Finished set_vm_metadata in 6.76 seconds
Rescued Bosh::Clouds::VMCreationFailed: #<Bosh::AzureCloud::AzureAsynchronousError: Bosh::AzureCloud::AzureAsynchronousError>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2388:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2436:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:377:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:559:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:127:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:180:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:133:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r3/bin/bundle:30:in `block in <main>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r3/bin/bundle:22:in `<main>'. backtrace: /var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:184:in `rescue in create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:18:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:180:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:133:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r3/bin/bundle:30:in `block in <main>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
```

**Comment by gossion** [comment]
Hi @ljfranklin , CPI already has retry logic for this case, see [code snippet](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/v35.0.0/src/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb#L590-L593). I think you can find message like "create_virtual_machine - Retry xx: will retry to create the virtual machine xxx which failed in provisioning" in your debug log, please check.

If it already retried and still failed, it is likely to be a platform issue. In this case, I think you can file a support ticket on Azure portal.

BTW, can you see error message like the format below in your debug log?
```
...
#Bosh::AzureCloud::AzureAsynchronousError: http_put - http code: xx
x-ms-client-request-id: xx
x-ms-request-id: xx
x-ms-correlation-request-id: xx
x-ms-routing-request-id: xx
Error message: {
  "error": {
    "code": "xx",
    "message": "xx",
    "details": [xx]
 ```
If not, CPI should return a more meaningful message.

**Comment by ljfranklin** [comment]
@joshzarrabi is that env still around for us to look at logs?

**Comment by bingosummer** [comment]
A fix is already released to return a better error message. Feel free to mention us and have it re-opened, if you still hit the issue.

**Comment by langered** [comment]
Hello @bingosummer && @gossion ,

we are using **BOSH 268.4** and **Azure CPI 35.4** and also getting the `Bosh::AzureCloud::AzureAsynchronousError` message but without additional information.

First we tried to deploy and got the following error message where the CPI actually created a VM but due to a CPI Error, Bosh doesn't know about it. Therefore, Bosh is not able to delete it. It gives a hint to delete resources manually:

```
| Creating missing vms:
 L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'This VM fails in provisioning after multiple retries.\nYou need to delete below resource manually after finishing investigation.\n
  Resource Group: ...
  Virtual Machine: ...
  Managed OS Disk: ...
  Managed Ephemeral Disk: ...
#<Bosh::AzureCloud::AzureAsynchronousError: The VM fails in provisioning but an error is thrown in cleanuping VM, os disk or ephemeral disk before retry.\n#<Bosh::AzureCloud::AzureAsynchronousError: Bosh::AzureCloud::AzureAsynchronousError>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2262:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2369:in `http_delete'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:626:in `delete_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:567:in `rescue in create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:520:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:112:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:174:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:132:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `load'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `<main>'>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:598:in `rescue in rescue in create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:565:in `rescue in create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:520:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:112:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:174:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:132:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `load'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `<main>'' in 'create_vm' CPI method
```

Then we try to re-deploy but it fails because of a blocking IP from the previous created VM. This VM was not deleted and the following error message does not contain any hint to delete the resources or any other additional information.

```
| Creating missing vms: ...
  L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<Bosh::AzureCloud::AzureAsynchronousError: Bosh::AzureCloud::AzureAsynchronousError>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2262:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:2310:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:369:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:538:in `create_virtual_machine'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:112:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:174:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:132:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `load'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `<main>'' in 'create_vm' CPI method
```

It would be helpful if also the second CPI error message could give a hint to this problem, like in the first CPI error.

Best regards,

@videlov && @langered

**Comment by beyhan** [comment]
are there any updates on progress or prioritization?
Thanks,
@beckermax, @beyhan

**Comment by h4xnoodle** [comment]
Hi @beyhan,

How often do you experience this issue? Is this during a large scale test? 

Thanks,
Rebecca

**Comment by BeckerMax** [comment]
Hi @h4xnoodle 
in the last months we occasionally see the error.
It did not happen during a large scale test. We saw it last on one of our azure production landscapes.

Best regards,
@FlorianNachtigall @beckermax
