### ISSUE TITLE
"bosh attach-disk" fails when VM CID contains semicolon. Needs to urlencode it.

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#594]
```
I, [2018-11-01T17:13:56.321727 #116]  INFO -- : Running bosh command --> /usr/local/bin/bosh --non-interactive --json --deployment bat attach-disk batlight/30a1033f-0330-46f4-96cb-b96ac0cd36b6 caching:None;disk_name:bosh-disk-data-b2c02b05-fd19-4e5a-a3ba-5e5ed703cac6;resource_group_name:binxicpi-hate-fang-rg 2>&1
sh: 1: disk_name:bosh-disk-data-b2c02b05-fd19-4e5a-a3ba-5e5ed703cac6: not found
I, [2018-11-01T17:14:31.511831 #116]  INFO -- : Bosh command failed: {
    "Tables": null,
    "Blocks": [
        "\nTask 30 | 17:14:30 | ",
        "Error: CPI error 'Bosh::Clouds::CloudError' with message 'This function should only be called for data disks' in 'attach_disk' CPI method (CPI request ID: 'cpi-583630')"
    ],
    "Lines": [
        "Using environment 'xxx.xx.xxx.xxx' as client 'admin'",
        "Using deployment 'bat'",
        "Task 30",
        "\n",
        "\n\nTask 30 Started  Thu Nov  1 17:14:30 UTC 2018\nTask 30 Finished Thu Nov  1 17:14:30 UTC 2018\nTask 30 Duration 00:00:00",
        "\nTask 30 error\n",
        "Expected task '30' to succeed but state is 'error'",
        "Exit code 1"
    ]
}sh: 1: resource_group_name:binxicpi-hate-fang-rg: not found

<-- rm /tmp/d20181101-116-19lxmze/deployment
BATs example failed  'with multiple persistent disks orphaning a disk and mounting a new disk cli can attach a disk' ./spec/system/persistent_disks_spec.rb:48 

  1) with multiple persistent disks orphaning a disk and mounting a new disk cli can attach a disk
     Failure/Error: bosh("attach-disk #{instance_id} #{volume_id}", deployment: single_disk_deploy.name)
     Bosh::Exec::Error:
       command '/usr/local/bin/bosh --non-interactive --json --deployment bat attach-disk batlight/30a1033f-0330-46f4-96cb-b96ac0cd36b6 caching:None;disk_name:bosh-disk-data-b2c02b05-fd19-4e5a-a3ba-5e5ed703cac6;resource_group_name:binxicpi-hate-fang-rg 2>&1' failed with exit code 127
     # ./lib/bat/bosh_runner.rb:25:in `bosh'
     # ./lib/bat/bosh_helper.rb:14:in `bosh'
     # ./spec/system/persistent_disks_spec.rb:57:in `block (3 levels) in <top (required)>'
```

I tried several ways to attach disks. Only one way can attach the disk successfully. That is to urlcode `;` to `%3B`. It's better to document it as a known issue if we don't have plans to change the id schema.

```
azureuser@binxi091701:~$ bosh -e azure -d cf attach-disk database/6672de96-12bf-4d84-af87-ebb88ddbe26c caching:None%3Bdisk_name:bosh-disk-data-8115562f-fc8f-4cb0-8578-c4e75cee7bba%3Bresource_group_name:binxi091701-vm-size
Using environment '10.0.0.4' as client 'admin'

Using deployment 'cf'

Task 353. Done

Succeeded
```

Other ways failed.
```
azureuser@binxi091701:~$ bosh -e azure -d cf attach-disk database/6672de96-12bf-4d84-af87-ebb88ddbe26c caching:None;disk_name:bosh-disk-data-8115562f-fc8f-4cb0-8578-c4e75cee7bba;resource_group_name:binxi091701-vm-size
Using environment '10.0.0.4' as client 'admin'

Using deployment 'cf'

Task 352

Task 352 | 03:08:26 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'This function should only be called for data disks' in 'attach_disk' CPI method (CPI request ID: 'cpi-819358')

Task 352 Started  Fri Nov  2 03:08:26 UTC 2018
Task 352 Finished Fri Nov  2 03:08:26 UTC 2018
Task 352 Duration 00:00:00
Task 352 error

Expected task '352' to succeed but state is 'error'

Exit code 1
disk_name:bosh-disk-data-8115562f-fc8f-4cb0-8578-c4e75cee7bba: command not found
resource_group_name:binxi091701-vm-size: command not found
azureuser@binxi091701:~$ bosh -e azure -d cf attach-disk database/6672de96-12bf-4d84-af87-ebb88ddbe26c 'caching:None;disk_name:bosh-disk-data-8115562f-fc8f-4cb0-8578-c4e75cee7bba;resource_group_name:binxi091701-vm-size'
Using environment '10.0.0.4' as client 'admin'

Using deployment 'cf'

Director responded with non-successful status code '404' response 'Endpoint '/disks/caching:None' not found. Please consider upgrading your director'

Exit code 1
azureuser@binxi091701:~$ bosh -e azure -d cf attach-disk database/6672de96-12bf-4d84-af87-ebb88ddbe26c "caching:None;disk_name:bosh-disk-data-8115562f-fc8f-4cb0-8578-c4e75cee7bba;resource_group_name:binxi091701-vm-size"
Using environment '10.0.0.4' as client 'admin'

Using deployment 'cf'

Director responded with non-successful status code '404' response 'Endpoint '/disks/caching:None' not found. Please consider upgrading your director'

Exit code 1
azureuser@binxi091701:~$ bosh -e azure -d cf attach-disk database/6672de96-12bf-4d84-af87-ebb88ddbe26c "caching:None\;disk_name:bosh-disk-data-8115562f-fc8f-4cb0-8578-c4e75cee7bba\;resource_group_name:binxi091701-vm-size"
Using environment '10.0.0.4' as client 'admin'

Using deployment 'cf'

Director responded with non-successful status code '404' response 'Endpoint '/disks/caching:None/' not found. Please consider upgrading your director'

Exit code 1

azureuser@binxi091701:~$ bosh -e azure -d cf attach-disk database/6672de96-12bf-4d84-af87-ebb88ddbe26c caching:None\;disk_name:bosh-disk-data-8115562f-fc8f-4cb0-8578-c4e75cee7bba\;resource_group_name:binxi091701-vm-size
Using environment '10.0.0.4' as client 'admin'

Using deployment 'cf'

Director responded with non-successful status code '404' response 'Endpoint '/disks/caching:None' not found. Please consider upgrading your director'

Exit code 1

```

**Comment by bingosummer** [comment]
BATs introduced a case https://github.com/cloudfoundry/bosh-acceptance-tests/commit/6c84d5a596863357d2d4d45dd50e1f79b454f512 for `attach_disk`, which will fail due to this issue. To bypass it for now, we should not use the latest BATs to run CPI pipeline.
