### ISSUE TITLE
Azure IMDS endpoint calls do not work when multiple UserAssigned managed identities are available

### ISSUE THREAD

**Issue by lodener** [cloudfoundry/bosh-azure-cpi-release#670]
### Versions
CPI      Version: 40.0.0
BOSH     Version: 274.1.0
CF       Version: 
Diego    Version:

### Stemcell
Version: bionic
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [X] Azure
- Location: West Europe
- Subscription ID:
- Resource Group Name:
- [X] Use Managed Disks

### Issue Details
Whenever the Azure IMDS endpoint is queried, a client_id does not appear to be specified in said query. This returns a 400 response when the call is made from a VM that has more than 1 managed identity assigned to it (as object_id, client_id or mi_res_id is [required](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token) when a VM has multiple identities).

### Logs
```
[Cmd Runner] 2022/09/27 11:14:50 DEBUG - Stderr: I, [2022-09-27T11:14:50.256470 #16614]  INFO -- [req_id ]: Starting create_stemcell...
I, [2022-09-27T11:14:50.257445 #16614 #2540] INFO --: _init_cpi_lock_dir: Initializing the CPI lock directory
D, [2022-09-27T11:14:50.823477 #16614 #2540] DEBUG --: The default storage account is '***'
I, [2022-09-27T11:14:50.824441 #16614 #2540] INFO --: http_get - trying to get https://management.azure.com/subscriptions/sub-id/resourceGroups/rg-name/providers/Microsoft.Storage/storageAccounts/sa-name?api-version=2017-10-01
I, [2022-09-27T11:14:50.824695 #16614 #2540] INFO --: get_token - trying to get/refresh Azure authentication token
D, [2022-09-27T11:14:50.824784 #16614 #2540] DEBUG --: Getting token from Azure VM Managed Service Identity
D, [2022-09-27T11:14:50.825056 #16614 #2540] DEBUG --: authentication_endpoint: http://169.254.169.254/metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.azure.com%2F&api-version=2018-02-01
D, [2022-09-27T11:14:50.825316 #16614 #2540] DEBUG --: request.header:
D, [2022-09-27T11:14:50.825401 #16614 #2540] DEBUG --: 	accept-encoding = gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2022-09-27T11:14:50.825473 #16614 #2540] DEBUG --: 	accept = */*
D, [2022-09-27T11:14:50.825541 #16614 #2540] DEBUG --: 	user-agent = BOSH-AZURE-CPI/37.3.0 pid-***
D, [2022-09-27T11:14:50.825611 #16614 #2540] DEBUG --: 	metadata = true
D, [2022-09-27T11:14:50.825677 #16614 #2540] DEBUG --: 	x-ms-client-request-id = ***
D, [2022-09-27T11:14:50.825746 #16614 #2540] DEBUG --: 	x-ms-return-client-request-id = true
D, [2022-09-27T11:14:50.894582 #16614 #2540] DEBUG --: get_token - 0: x-ms-client-request-id:
I, [2022-09-27T11:14:50.895380 #16614]  INFO -- [req_id ]: Finished create_stemcell in 0.64 seconds
[Cmd Runner] 2022/09/27 11:14:50 DEBUG - Successful: true (0)
[cpiCmdRunner] 2022/09/27 11:14:50 DEBUG - Exit Code 0 when executing external CPI command '/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/jobs/azure_cpi/bin/cpi'
STDIN: '{"method":"create_stemcell","arguments":["/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/tmp/stemcell-manager1395363849/image",{"architecture":"x86_64","container_format":"bare","disk":3072,"disk_format":"vhd","hypervisor":"hyperv","infrastructure":"azure","name":"bosh-azure-hyperv-ubuntu-bionic-go_agent","os_distro":"ubuntu","os_type":"linux","root_device_name":"/dev/sda1","version":"1.97"}],"context":{"director_uuid":"***","vm":{"stemcell":{"api_version":3}}},"api_version":2}'
STDOUT: '{"result":null,"error":{"type":"Bosh::AzureCloud::AzureError","message":"get_token - http code: 400. Azure authentication failed: Bad request. Please assure no typo in values of tenant_id, client_id or client_secret/certificate. Error message: {\"error\":\"invalid_request\",\"error_description\":\"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request\"}","ok_to_retry":false},"log":"Rescued Bosh::AzureCloud::AzureError: get_token - http code: 400. Azure authentication failed: Bad request. Please assure no typo in values of tenant_id, client_id or client_secret/certificate. Error message: {\"error\":\"invalid_request\",\"error_description\":\"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request\"}. backtrace: /root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:2260:in `get_token'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:2351:in `http_get_response'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:2504:in `http_get'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:133:in `get_resource_by_id'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:1888:in `get_storage_account'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:1876:in `get_storage_account_by_name'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/storage/storage_account_manager.rb:140:in `default_storage_account'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/meta_store/table_manager.rb:10:in `initialize'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:834:in `new'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:834:in `_init_azure'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:84:in `block in create_stemcell'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/telemetry/telemetry_manager.rb:71:in `monitor'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:83:in `create_stemcell'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/vendor/bundle/ruby/3.1.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `public_send'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/vendor/bundle/ruby/3.1.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `run'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/cli/exec.rb:58:in `load'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/cli/exec.rb:23:in `run'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:484:in `exec'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:31:in `dispatch'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/cli.rb:25:in `start'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/site_ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/bin/bundle:25:in `load'\n/root/.bosh/installations/0e702891-ff7f-4493-55cf-4a6876988937/packages/ruby-3.1.0-r0.81.0/bin/bundle:25:in `<main>'"}'
STDERR: 'I, [2022-09-27T11:14:50.256470 #16614]  INFO -- [req_id ]: Starting create_stemcell...
```

### Repro steps
- Assign more than 1 UserAssigned managed identity to a VM
- From this VM, make use of the [request_from_managed_identity_endpoint](https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/60e6487c28da9f89c47de31d906df5abc25c461d/src/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb#L2305) function (only resource and api-version are specified in the params)

To manually mimic this behaviour:
- From a VM with multiple managed identities, run:
- `curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s`
Response:
`{"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}`

To get a proper token when having more than 1 managed identity, the client_id of one of the assigned managed identities has to be included in the IMDS query:
- `curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F&client_id=***' -H Metadata:true -s`
Response: `{"access_token":"***","client_id":"***","expires_in":"85283","expires_on":"1664363551","ext_expires_in":"86399","not_before":"1664276851","resource":"https://management.azure.com/","token_type":"Bearer"}`

**Comment by lodener** [comment]
We assign multiple managed identities to our concourse workers through Azure Devops pipelines, from which we can then simply `az login --identity -u /subscriptions/${subscription}>/resourcegroups/${resource-group}providers/Microsoft.ManagedIdentity/userAssignedIdentities/${managed-identity}`. We use this to manage multiple Azure subscriptions from these worker VMs.

This works great for us, however the bosh-azure-cpi implementation does not currently handle IMDS calls properly when run from a VM with more than 1 managed identity attached to it, as it is missing the parameters Azure requires when a VM has multiple identities assigned to it (see https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http).

**Comment by ramonskie** [comment]
we would gladly review a PR where this issue is addressed
